name: Publish Obsidian Notes

on:
  push:
    branches:
      - vault

permissions:
  contents: write

jobs:
  publish:

    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: vault

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Convert Markdown
        run: |
          python obsidian-to-github-md.py

      ########################################################

      - name: Checkout Deploy Branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: deploy
          fetch-depth: 1

      ########################################################

      - name: Sync Published Files
        run: |

          rsync -a --delete .temp_publish/Published/ deploy/Published/

      ########################################################

      - name: Commit and Push
        working-directory: deploy
        run: |

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --cached --quiet; then
            echo "No changes to publish."
            exit 0
          fi

          git commit -m "${{ github.event.head_commit.message }}"

          git push origin main